variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build and test:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add black=20.8_beta1-r0 py3-flake8 docker-compose make
  script:
    - cd contrib/docker
    - make build
    - make update-db
    - make test-all
    - cd ../..
    - make check
