variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build and test:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add black py3-flake8 py3-isort make
  script:
    - cd contrib/docker
    - make build
    - docker compose up -d db
    - make update-db
    - make test-all
    - cd ../..
    - make check
